FROM node

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
# COPY ./angular-node-express-api/bin ./bin
# COPY ./angular-node-express-api/dist ./dist
# COPY ./angular-node-express-api/routes ./routes
# COPY ./angular-node-express-api/package.json ./package.json
# COPY ./angular-node-express-api/package-lock.json ./package-lock.json

COPY angular-node-express-api .

EXPOSE 37903

CMD [ "node", "app.js" ]